### ISSUE TITLE
Python Versions showing "Waiting for data" but nothing else

### ISSUE THREAD

**Issue by rpgdev** [badarsebard/pyden-suite#1]
I just installed your app and I'm getting the following screen when triying to install new python. It mentions a red and green button but I don't see any, is this screen working as expected? Am I supposed to use the web interface for this or should I use the command line?

<img width="950" alt="image" src="https://user-images.githubusercontent.com/20094474/52352446-93381600-29fa-11e9-82cc-5c7637a9f017.png">

This is my version info:
Splunk Enterprise
Version: 7.2.3
Build: 06d57c595b80

**Comment by badarsebard** [comment]
We'll need to identify where the search is stalling. Please run the search in a search page and open the Job Inspector. The command with the highest time should be the part of the pipeline where it's failing. Additionally, if you can provide the search.log from the Job Inspector that should show any errors that are being thrown.

**Comment by rpgdev** [comment]
Here's the [search.log](https://github.com/badarsebard/pyden-suite/files/2837330/search.log)

**Comment by badarsebard** [comment]
Not seeing any errors in the log. Any chance you can run the search one pipe at a time and see where the failure occurs?

**Comment by rpgdev** [comment]
This is part of the inspector report:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/20094474/52363848-bf12c600-2a11-11e9-8f09-ee2173b5fb72.png">

Running search: 
`| getversions | lookup versionstatus version | rex field=version "(?<v_M>\d+)\.(?<v_m>\d+)\.(?<v_mm>\d+)" | eval v_M=tonumber(v_M), v_m=tonumber(v_m), v_mm=tonumber(v_mm) | sort -v_M, -v_m, -v_mm | table status, version `

One pipe at a time always gave me a result and didn't really take very long. Could this be a permissions issue?

**Comment by badarsebard** [comment]
So if I understand correctly the search functions correctly from the search page but the table doesn't show results?

**Comment by rpgdev** [comment]
That seemed to be the case but it's working fine now. It seems that restarting splunk from the command line made the difference even though I did restart it  it when it prompted me to do so after installing the app from splunkbase. I apologise, it just occurred to me to restart the app from the cli I should've done it earlier :facepalm: (again, I did restart it when splunkbased prompted me to, apparently it's not the same as doing it from the cli as I assumed). Anyways, proud to have posted issue #1 and thank you for publishing this suite. Without it my current Splunk app project might not see the light of day. I still need to make it all work though ;)

**Comment by badarsebard** [comment]
Happy to help! I'd also love to see the app you're working on if it's open source. I'm trying to be as hands on as possible with early adopters so I can tailor the suite to your needs and fix any unknown bugs as fast as possible so I don't hold up your development. Feel free to reach out to me over the Splunk usergroup slack @badarsebard.

**Comment by rpgdev** [comment]
The app is not public yet but once it is I'll let you know.
