### ISSUE TITLE
pyden-manager sending huge bundles in a distributed search environment

### ISSUE THREAD

**Issue by dtomlinson91** [badarsebard/pyden-suite#10]
I had a problem in prd on indexers which were configured as peers for a search head cluster.

The bundle from the searchhead includes everything in `$SPLUNK_HOME/etc/apps/pyden-manager` by default. This includes the `bin` folder which contains the python builds.

As we were running reports every 2 minutes and using pyden on the results, the Search Heads were pushing this bundle every 2 minutes which took up a fair bit of space. (Not all of it was able to be diff'd resulting in the binary files being sent multiple times).

I can't think of any good reason why a search peer needs `pyden-manager/bin` - this should only be needed on a search head, never an indexer.

`distsearch.conf` has a `replicationBlacklist` stanza for this purpose, I propose a pull request that sets a regex to match `pyden-manager/bin` (the setting only applies to `$SPLUNK_HOME/etc`), is this something that is welcomed?

I can appreciate not many people would run into the issue, but the stanza is there for exactly this purpose, and although I've successfully made the change locally, it might be nice to prevent it happening again if anyone else configures pyden in a distributed search environment.

**Comment by badarsebard** [comment]
I'll take a look at the PR as soon as I can, but I have to strongly recommend not running the manager app in production. The manager should be run in an isolated environment and then the compiled PyDen app distributed to production.

**Comment by dtomlinson91** [comment]
Yeah you're absolutely right, I (mistakenly) thought they were coupled together. If they aren't I'll remove the pyden manager from the deployer and just use the pyden app. I don't think a PR is necessary if I deployed it incorrectly, I mistakenly took from the docs that the pyden app and manager should be ran together - I didn't think to do this on an isolated instance and just copy the compiled app onto the deployer. Maybe we could add this to the documentation instead?

**Comment by badarsebard** [comment]
Definitely good feedback on the docs. If you're using a deployer to push the app to a search head cluster you could run the manager on the deployer as long as you have good access controls for it. 

Since the manager has the capability to reach out to PyPI it poses a security risk if users aren't aware of the consequences.

**Comment by dtomlinson91** [comment]
> Since the manager has the capability to reach out to PyPI it poses a security risk if users aren't aware of the consequences.

Good point, we're behind a proxy which is open to pypi from our subnet but I didn't even think of the fact that the SHs would push files to indexers that are not open to pypi. I'll be sure to remove the manager from the deployer - much simpler (and safer) to just compile, check it over, and copy across. 

This is probably the most underrated app on splunkbase - we're heavily invested in Splunk and pyden has made my job incredibly less painful since discovering it last year. Cheers.
