### ISSUE TITLE
in plain splunk7.2, on RHEL the pydelete command doesn't do anything

### ISSUE THREAD

**Issue by owenBeresford** [badarsebard/pyden-suite#6]
Hi.
I'm the guy who opened the pull reqt a few days ago. 
I am now looking at delete cmd.

Using the pyden-manager GUI, and the versions list. 
If i hit the delete "minus symbol" it sends "| pydelete $version" to the server , as a oneshot reqt

HOWEVER if i refresh the page the version is still there, as though I hadn't clicked on delete.
I have added logging to the pydelete script, then for test purposes a syntax typo (and restart service).
Nothing reports to any log files, or to me on the API response that I tried to exec a script with a typo.   Does it work to exec scripts with side-effects using oneshot?

I will update the ticket/ another pull request if I can solve the issue

**Comment by badarsebard** [comment]
This is a big I've noticed but haven't exactly identified the issue. I've got some commits in a local branch that improve the logging to help identify some of these issues. I'll be making some commits after the new year when I get back from vacation. For this particular issue m guess is that there's an issue in the pydelete script with the directory removal.

**Comment by badarsebard** [comment]
Are you still experiencing this in the latest version? The new test bed is set to verify the delete functionality and everything has come back successful. Albeit the test bed is new so there could well be a gap.
