### ISSUE TITLE
exec pyden under python3 crashes

### ISSUE THREAD

**Issue by owenBeresford** [badarsebard/pyden-suite#7]
pyden 1.24, 
RHEL7
splunk8

I'm using your pyden to be able to use pip.  I am porting working code of an app deployed version of a driver, to a pip managed version. 

In the new version, at the top of my script, I add directories to os.path; then have `import activate_default`
The activate.py file runs importlib.reload() on sys; which wipes those alterations.
This then crashes as it cant see the splunk directory anymore.

splunk/persistentconn/appserver.py: No module named splunk

Would you  be happy **if i added a callback update_path**; to allow repairing the sys.path ?

**Comment by owenBeresford** [comment]
I have avoided the issue, in a fairly stable/ non-hacky fashion by adding PYTHONPATH to the execve call ENV object.
When splunk stops dying i will write a patch

**Comment by badarsebard** [comment]
At some point I will be adding a feature to allow a developer to specify the ENV object within a .conf file.

**Comment by owenBeresford** [comment]
Hi,
I'm looking at a "multi-site" splunk, i.e. a single Splunk node which hosts several apps/ routine reports; which may need a different env for each app using Pyden.
I suspect you where envisioning adding a "single-site" Splunk, which therefore has a single Pyden config.

I have created myself some code that implements your idea
