### ISSUE TITLE
Running pyden in py3 (all OS)

### ISSUE THREAD

**Issue by owenBeresford** [badarsebard/pyden-suite#8]
As py2.7 will no longer be supported by python.org as of jan 2nd 2020; we are planning to sell a py3 based splunk solution to all clients.
**Would you like  branch of changes to your scripts that are patched to support py3?**
To see issue::
* install splunk8
* install pyden* apps
* edit /opt/splunk/etc/system/local/server.conf to have python.version=force_python3
* restart splunk
* use pyden-manager GUI

What is your plan for enterprise people (with current elderly splunk) vs new-to-splunk people (who will start with splunk8).

**Comment by owenBeresford** [comment]
My dev copy is complete. i can upload when you respond

**Comment by badarsebard** [comment]
Issue resolved with v1.3.0
